-- MySQL Script generated by MySQL Workbench
-- 10/13/15 17:07:20
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema jardin
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema jardin
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `jardin` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `jardin` ;

-- -----------------------------------------------------
-- Table `jardin`.`educadora`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jardin`.`educadora` (
  `rut_educadora` VARCHAR(7) NOT NULL,
  `password` VARCHAR(15) NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  `email` VARCHAR(80) NOT NULL,
  `administrador` TINYINT(1) NULL,
  PRIMARY KEY (`rut_educadora`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jardin`.`Administrador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jardin`.`Administrador` (
  `contraseña` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `rut_administrador` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`rut_administrador`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jardin`.`parvulo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jardin`.`parvulo` (
  `rut_parvulo` VARCHAR(8) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `fecha_nacimiento` DATE NOT NULL,
  `talla` INT NULL,
  `peso` FLOAT NULL,
  PRIMARY KEY (`rut_parvulo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jardin`.`noticia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jardin`.`noticia` (
  `id_noticia` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(100) NOT NULL,
  `descripcion` VARCHAR(500) NOT NULL,
  `importante` TINYINT(1) NOT NULL,
  `fecha` DATE NOT NULL,
  PRIMARY KEY (`id_noticia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jardin`.`foto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jardin`.`foto` (
  `id_foto` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(100) NOT NULL,
  `link` VARCHAR(250) NOT NULL,
  PRIMARY KEY (`id_foto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jardin`.`asistencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jardin`.`asistencia` (
  `id_asistencia` INT NOT NULL,
  `fecha` DATE NOT NULL,
  `rut_parvulo` VARCHAR(8) NOT NULL,
  INDEX `fk_Asistencia_Parvulo1_idx` (`rut_parvulo` ASC),
  PRIMARY KEY (`rut_parvulo`, `id_asistencia`),
  CONSTRAINT `fk_Asistencia_Parvulo1`
    FOREIGN KEY (`rut_parvulo`)
    REFERENCES `jardin`.`parvulo` (`rut_parvulo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jardin`.`hito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jardin`.`hito` (
  `id_hito` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(500) NOT NULL,
  `fecha` DATE NOT NULL,
  `rut_parvulo` VARCHAR(8) NOT NULL,
  PRIMARY KEY (`id_hito`, `rut_parvulo`),
  INDEX `fk_Hito_Parvulo1_idx` (`rut_parvulo` ASC),
  CONSTRAINT `fk_Hito_Parvulo1`
    FOREIGN KEY (`rut_parvulo`)
    REFERENCES `jardin`.`parvulo` (`rut_parvulo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jardin`.`imprevisto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jardin`.`imprevisto` (
  `id_imprevisto` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(500) NOT NULL,
  `fecha` DATE NOT NULL,
  `rut_parvulo` VARCHAR(8) NOT NULL,
  PRIMARY KEY (`id_imprevisto`, `rut_parvulo`),
  INDEX `fk_Imprevisto_Parvulo_idx` (`rut_parvulo` ASC),
  CONSTRAINT `fk_Imprevisto_Parvulo`
    FOREIGN KEY (`rut_parvulo`)
    REFERENCES `jardin`.`parvulo` (`rut_parvulo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jardin`.`documento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jardin`.`documento` (
  `id_documento` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `link` VARCHAR(250) NOT NULL,
  `fecha` DATE NOT NULL,
  PRIMARY KEY (`id_documento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jardin`.`educadora_gestiona_noticia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jardin`.`educadora_gestiona_noticia` (
  `id_noticia` INT NOT NULL,
  `rut_educadora` VARCHAR(7) NOT NULL,
  `tipo_log` VARCHAR(45) NULL,
  `fecha` DATETIME NULL,
  PRIMARY KEY (`id_noticia`, `rut_educadora`),
  INDEX `fk_noticia_has_educadora_educadora1_idx` (`rut_educadora` ASC),
  INDEX `fk_noticia_has_educadora_noticia1_idx` (`id_noticia` ASC),
  CONSTRAINT `fk_noticia_has_educadora_noticia1`
    FOREIGN KEY (`id_noticia`)
    REFERENCES `jardin`.`noticia` (`id_noticia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_noticia_has_educadora_educadora1`
    FOREIGN KEY (`rut_educadora`)
    REFERENCES `jardin`.`educadora` (`rut_educadora`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jardin`.`educadora_gestiona_documento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jardin`.`educadora_gestiona_documento` (
  `educadora_rut_educadora` VARCHAR(7) NOT NULL,
  `documento_id_documento` INT NOT NULL,
  `tipo_log` VARCHAR(45) NULL,
  `fecha` DATETIME NULL,
  PRIMARY KEY (`educadora_rut_educadora`, `documento_id_documento`),
  INDEX `fk_educadora_has_documento_documento1_idx` (`documento_id_documento` ASC),
  INDEX `fk_educadora_has_documento_educadora1_idx` (`educadora_rut_educadora` ASC),
  CONSTRAINT `fk_educadora_has_documento_educadora1`
    FOREIGN KEY (`educadora_rut_educadora`)
    REFERENCES `jardin`.`educadora` (`rut_educadora`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_educadora_has_documento_documento1`
    FOREIGN KEY (`documento_id_documento`)
    REFERENCES `jardin`.`documento` (`id_documento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jardin`.`educadora_gestiona_foto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jardin`.`educadora_gestiona_foto` (
  `educadora_rut_educadora` VARCHAR(7) NOT NULL,
  `foto_id_foto` INT NOT NULL,
  `tipo_log` VARCHAR(45) NULL,
  `fecha` DATETIME NULL,
  PRIMARY KEY (`educadora_rut_educadora`, `foto_id_foto`),
  INDEX `fk_educadora_has_foto_foto1_idx` (`foto_id_foto` ASC),
  INDEX `fk_educadora_has_foto_educadora1_idx` (`educadora_rut_educadora` ASC),
  CONSTRAINT `fk_educadora_has_foto_educadora1`
    FOREIGN KEY (`educadora_rut_educadora`)
    REFERENCES `jardin`.`educadora` (`rut_educadora`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_educadora_has_foto_foto1`
    FOREIGN KEY (`foto_id_foto`)
    REFERENCES `jardin`.`foto` (`id_foto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
